name: 'Hello World'
description: 'Cache builds to speed up openwrt compile'
inputs:
  ccache:
    description: 'check if to store ccache'
    required: true
    default: 'true'
  toolchain:
    description: 'check if to store toolchain'
    required: true
    default: 'true'
outputs:
  hit:
    description: 'indicate cache found'
runs:
  using: 'node12'
  main: 'fetch.js'
  post: 'save.js'
  post-if: 'success()'
branding:
  icon: 'archive'
  color: 'gray-dark'
